Add `preferNative` option
shuding/react-wrap-balancer pull request #77
Opened 2023-07-15 04:43 UTC by lucasweng

Provide an option to opt out of the native CSS text-balancing when the `text-wrap: balance` can't serve the needs or a customized ratio is preferred.

Closes https://github.com/shuding/react-wrap-balancer/issues/75.

2023-07-19 11:30 UTC, shuding requested changes
Can you add the same option to `Provider` as well? And adjust the provider to pass it down. Thanks!

2023-07-19 15:43 UTC, lucasweng commented on src/index.tsx
> +  const preferNativeBalancing = preferNative && contextValue.preferNative
Hey @shuding,
Should `Balancer` be able to override the `preferNative` context value when the provider passes `false`? It seems to me overriding the `true` value from context is more likely to happen, as the case mentioned in https://github.com/shuding/react-wrap-balancer/issues/75 🤔 So, it only allows overriding `preferNative: true` for now. What are your thoughts on this? Thanks!

2023-07-20 20:55 UTC, shuding commented on src/index.tsx
> +  const preferNativeBalancing = preferNative && contextValue.preferNative
Yes I think it should be able to override. Maybe we can extend this context to be an array or an object to contain more information if necessary.

2023-07-21 01:17 UTC, lucasweng commented on src/index.tsx
> +  const preferNativeBalancing = preferNative && contextValue.preferNative
Updated `Balancer` in https://github.com/shuding/react-wrap-balancer/pull/77/commits/b9ceaa17f715e657332187a34f194f134e527240.

If `preferNative` is not provided to `Balancer`, the `??` operator will take the value from the context, which defaults to `true` in `createContext` and in `Provider`. So when `preferNative` is explicitly provided, it can override.
```diff
@@ -184,7 +184,7 @@ const Provider: React.FC<{

 const Balancer = <ElementType extends React.ElementType = React.ElementType>({
   ratio = 1,
-  preferNative = true,
+  preferNative,
   nonce,
   children,
   ...props
@@ -192,7 +192,7 @@ const Balancer = <ElementType extends React.ElementType = React.ElementType>({
   const id = useId()
   const wrapperRef = React.useRef<WrapperElement>()
   const contextValue = React.useContext(BalancerContext)
-  const preferNativeBalancing = preferNative && contextValue.preferNative
+  const preferNativeBalancing = preferNative ?? contextValue.preferNative
   const Wrapper: React.ElementType = props.as || 'span'

```

2023-07-26 05:46 UTC, shuding approved these changes
Thank you!

2023-07-26 05:46 UTC, merged